-- Insert statements for Area_Manager Table

INSERT INTO AREA_MANAGER VALUES ('E001', 'Plano');

INSERT INTO AREA_MANAGER VALUES ('E003', 'Frisco');

INSERT INTO AREA_MANAGER VALUES ('E005', 'Richardson');

INSERT INTO AREA_MANAGER VALUES ('E007', 'McKinney');