-- Insert statements into Comment Table

INSERT INTO COMMENTS VALUES('SHOP2', 'C005','10', 'GOOD PLACE');

INSERT INTO COMMENTS VALUES('SHOP5', 'C004','10', 'NICE PLACE');

INSERT INTO COMMENTS VALUES('SHOP7', 'C003','8', 'AVERAGE PLACE');