-- Insert statements for Gold-Member Table

INSERT INTO GOLD_MEMBER VALUES (‘G001’, ‘GOLD1’);

INSERT INTO GOLD_MEMBER VALUES (‘G002’, ‘GOLD2’);

INSERT INTO GOLD_MEMBER VALUES (‘G003’, ‘GOLD3’);

INSERT INTO GOLD_MEMBER VALUES (‘G004’, ‘GOLD4’);

INSERT INTO GOLD_MEMBER VALUES (‘G005’, ‘GOLD5’);

INSERT INTO GOLD_MEMBER VALUES (‘G006’, ‘GOLD6’);

INSERT INTO GOLD_MEMBER VALUES (‘G007’, ‘GOLD7’);

INSERT INTO GOLD_MEMBER VALUES (‘G008’, ‘GOLD8’);

INSERT INTO GOLD_MEMBER VALUES (‘G009’, ‘GOLD9’);

INSERT INTO GOLD_MEMBER VALUES (‘G010’, ‘GOLD10’);