-- Insert statements into Order_Items Table

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O001', 'ICECREAM VANILLA');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O001', 'ICECREAM CHOCOLATE');

INSERT INTO ORDER_ITEMS VALUES ('C002', 'O002', 'CHOWMEIN FAMILY PACK');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O003', 'CAPPUCCINO');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O003', 'CHOCOLATE FRAPPE');

INSERT INTO ORDER_ITEMS VALUES ('C004', 'O004', 'CHOCOLATE CHIP PANCAKES');

INSERT INTO ORDER_ITEMS VALUES ('C005', 'O005', 'STUFFED PUFF PASTRY');

INSERT INTO ORDER_ITEMS VALUES ('C006', 'O006', 'CHEESE CAKE');

INSERT INTO ORDER_ITEMS VALUES ('C006', 'O006', 'CREME BRULEE');

INSERT INTO ORDER_ITEMS VALUES ('C007', 'O007', 'ORANGE CHICKEN');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O008', 'BANANA PANCAKES');

INSERT INTO ORDER_ITEMS VALUES ('C002', 'O009', 'FRIES');

INSERT INTO ORDER_ITEMS VALUES ('C002', 'O010', 'MANGO CAKE');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O011', 'BLUEBERRY ICE CREAM');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O011', 'OREO ICE CREAM' );

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O012', 'FRIED CHICKEN');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O013', 'OATMEAL PANCAKES');

INSERT INTO ORDER_ITEMS VALUES ('C007', 'O014', 'BOBA TEA');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O015', 'BROWNIES');

INSERT INTO ORDER_ITEMS VALUES ('C002', 'O016','VANILLA');

INSERT INTO ORDER_ITEMS VALUES ('C002', 'O016','MIXED FRUIT ICE CREAM');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O017', 'CHICKEN FRIED RICE');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O017', 'SHRIMP FRIED RICE');

INSERT INTO ORDER_ITEMS VALUES ('C004', 'O018', 'ALL MEAL PANCAKES');

INSERT INTO ORDER_ITEMS VALUES ('C005', 'O019', 'CHICKEN POPCORN');

INSERT INTO ORDER_ITEMS VALUES ('C006', 'O020', 'RED VELVET CAKE');

INSERT INTO ORDER_ITEMS VALUES ('C007', 'O021','MANGO ICECREAM');

INSERT INTO ORDER_ITEMS VALUES ('C001', 'O022', 'CHICKEN CHOW MEIN');

INSERT INTO ORDER_ITEMS VALUES ('C003', 'O023', 'PASSION FRUIT PANCAKES');

INSERT INTO ORDER_ITEMS VALUES ('C004', 'O024', 'BURGER WITH FRIES');

INSERT INTO ORDER_ITEMS VALUES ('C005', 'O025', 'LYCHEE TART');

INSERT INTO ORDER_ITEMS VALUES ('C005', 'O025', 'EGG TART');