-- Insert statements into Product Table

INSERT INTO PRODUCT VALUES ('PEN', '234');

INSERT INTO PRODUCT VALUES ('MAGGI', '34');

INSERT INTO PRODUCT VALUES ('SANITISER', '0');

INSERT INTO PRODUCT VALUES ('MASK', '4');

INSERT INTO PRODUCT VALUES ('MASALA', '24');

INSERT INTO PRODUCT VALUES ('SOY SAUCE', '94');

INSERT INTO PRODUCT VALUES ('RICE', '784');

INSERT INTO PRODUCT VALUES ('NOODLES', '98');

INSERT INTO PRODUCT VALUES ('BOOKS', '894');

INSERT INTO PRODUCT VALUES ('WATER BOTTLES', '77778');