-- Insert statements into Promotion Table

INSERT INTO PROMOTION VALUES('SHOP2', 'GET20', 'GET 20% OFF');

INSERT INTO PROMOTION VALUES('SHOP3', 'GET30', 'GET 30% OFF');

INSERT INTO PROMOTION VALUES('SHOP5', 'BUY20', 'GET 20% OFF');

INSERT INTO PROMOTION VALUES('SHOP6', 'SIX20', 'GET 20% OFF');

INSERT INTO PROMOTION VALUES('SHOP7', 'SALE20', 'GET 20% OFF');