-- Insert statements into Restaurant_Type Table

INSERT INTO RESTAURANT_TYPE VALUES('SHOP2', 'ICE CREAM PLACE');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP3', 'CHINESE');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP3', 'NOODLES');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP5', 'CAFE');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP5', 'PANCAKE PLACE');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP6', 'FAST FOOD');

INSERT INTO RESTAURANT_TYPE VALUES('SHOP7', 'DESERT');