-- Insert statements for Restaurant Table

INSERT INTO RESTAURANT VALUES('SHOP2');

INSERT INTO RESTAURANT VALUES('SHOP3');

INSERT INTO RESTAURANT VALUES ('SHOP5');

INSERT INTO RESTAURANT VALUES('SHOP6');

INSERT INTO RESTAURANT VALUES('SHOP7');