-- Insert statements into Sells Table

INSERT INTO SELLS VALUES('SHOP1', 'PEN', '5');

INSERT INTO SELLS VALUES('SHOP4', 'PEN', '4');

INSERT INTO SELLS VALUES('SHOP1', 'MAGGI', '12');

INSERT INTO SELLS VALUES('SHOP4', 'MAGGI', '12');

INSERT INTO SELLS VALUES('SHOP1', 'SANITISER', '2');

INSERT INTO SELLS VALUES('SHOP4', 'SANITISER', '5');

INSERT INTO SELLS VALUES('SHOP1', 'MASK', '5');

INSERT INTO SELLS VALUES('SHOP4', 'MASK', '3');

INSERT INTO SELLS VALUES('SHOP1', 'MASALA', '1');

INSERT INTO SELLS VALUES('SHOP4', 'MASALA', '2');

INSERT INTO SELLS VALUES('SHOP1', 'SOY SAUCE', '5');

INSERT INTO SELLS VALUES('SHOP4', 'SOY SAUCE', '5');

INSERT INTO SELLS VALUES('SHOP1', 'RICE', '30');

INSERT INTO SELLS VALUES('SHOP4', 'RICE', '29');

INSERT INTO SELLS VALUES('SHOP1', 'BOOKS', '2');

INSERT INTO SELLS VALUES('SHOP4', 'BOOKS', '1');

INSERT INTO SELLS VALUES('SHOP1', 'NOODLES', '5');

INSERT INTO SELLS VALUES('SHOP4', 'NOODLES', '5');

INSERT INTO SELLS VALUES('SHOP1', 'WATER BOTTLES', '15');

INSERT INTO SELLS VALUES('SHOP4', 'WATER BOTTLES', '14');